/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-05 04:47:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.unitime.timetable.ApplicationProperties;
import org.cpsolver.ifs.util.JProf;
import java.text.NumberFormat;
import org.unitime.timetable.StartupService;
import org.unitime.timetable.spring.SpringApplicationContextHolder;
import org.unitime.timetable.util.Constants;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/tld/localization.tld", Long.valueOf(1596536222000L));
    _jspx_dependants.put("jar:file:/home/nhtlong/tomcat-stuffed/webapps/ROOT/WEB-INF/lib/struts-taglib-1.3.10.jar!/META-INF/tld/struts-logic.tld", Long.valueOf(1227893410000L));
    _jspx_dependants.put("/initializationError.jspf", Long.valueOf(1580200622000L));
    _jspx_dependants.put("/WEB-INF/tld/timetable.tld", Long.valueOf(1580200626000L));
    _jspx_dependants.put("jar:file:/home/nhtlong/tomcat-stuffed/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1580200622000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.10.jar", Long.valueOf(1580200624000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.unitime.timetable.ApplicationProperties");
    _jspx_imports_classes.add("org.unitime.timetable.StartupService");
    _jspx_imports_classes.add("org.unitime.timetable.spring.SpringApplicationContextHolder");
    _jspx_imports_classes.add("org.cpsolver.ifs.util.JProf");
    _jspx_imports_classes.add("org.unitime.timetable.util.Constants");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005floc_005frtl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fcopy_0026_005fbr_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005floc_005frtl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fcopy_0026_005fbr_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005floc_005frtl.release();
    _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.release();
    _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fcopy_0026_005fbr_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<HTML>\n");
      out.write("	<HEAD>\n");
      out.write("	    <meta charset=\"UTF-8\"/>\n");
      out.write("	    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n");
      out.write(" 	   <link type=\"text/css\" rel=\"stylesheet\" href=\"unitime/gwt/standard/standard.css\">\n");
      out.write(" 	   <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime.css\">\n");
      out.write(" 	   <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime-mobile.css\">\n");
      out.write(" 	   <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/timetabling.css\">\n");
      out.write(" 	   ");
      if (_jspx_meth_loc_005frtl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		<link rel=\"shortcut icon\" href=\"images/timetabling.ico\" />\n");
      out.write("	    <script type=\"text/javascript\" language=\"javascript\" src=\"unitime/unitime.nocache.js\"></script>\n");
      out.write("		<TITLE>UniTime ");
      out.print(Constants.VERSION);
      out.write("</TITLE>\n");
      out.write("	</HEAD>\n");
      out.write("	<BODY class=\"bodyMain\" onload=\"document.forms[0].username.focus();\">\n");
      out.write("	\n");
      out.write("	");
 if (ApplicationProperties.getProperty("tmtbl.header.external", "").trim().length()>0) { 
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, ApplicationProperties.getProperty("tmtbl.header.external"), out, true);
      out.write('\n');
      out.write('	');
 } 
      out.write("\n");
      out.write("	\n");
      out.write("	<span class='top-menu'>\n");
      out.write("    	<span id='UniTimeGWT:TopMenu' style=\"display: block; height: 23px;\"></span>\n");
      out.write("    </span>\n");
      out.write("\n");
      out.write("	");
      if (_jspx_meth_tt_005fhasProperty_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fhasProperty_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fhasProperty_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('\n');

	String errorMsg = null;
	if (request.getParameter("e")!=null) {
		String eNum = request.getParameter("e");
		if (eNum.equals("1"))
			errorMsg = "Invalid username/password";
		if (eNum.equals("2"))
			errorMsg = "Authentication failed";
		if (eNum.equals("3"))
			errorMsg = "Authentication failed";
		if (eNum.equals("4"))
			errorMsg = "User temporarily locked out -<br> Exceeded maximum failed login attempts.";
	} else if (request.getParameter("m")!=null) {
		errorMsg = (String)request.getParameter("m");
	}
 
      out.write("		\n");
      out.write("\n");
      out.write("<FORM name=\"f\" action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" method=\"POST\">\n");
      out.write("	<INPUT type=\"hidden\" name=\"cs\" value=\"login\">\n");
      out.write("	<INPUT type=\"hidden\" name=\"menu\" value=\"");
      out.print(request.getParameter("menu") == null ? "" : request.getParameter("menu") );
      out.write("\">\n");
      out.write("	<INPUT type=\"hidden\" name=\"target\" value=\"");
      out.print(request.getParameter("target") == null ? "" : request.getParameter("target") );
      out.write("\">\n");
      out.write("			\n");
      out.write("	<span class='unitime-Login'>\n");
      out.write("		<span class=\"mobile-menu-button\" id='UniTimeGWT:MobileMenuButton'></span>\n");
      out.write("		<span class='logo'><img src=\"images/unitime.png\" border=\"0\" alt=\"UniTime\"></span>\n");
      out.write("		<span class='header'>\n");
      out.write("			<div class='h1'>University Timetabling</div>\n");
      out.write("			<div class='h2'>Comprehensive Academic Scheduling Solutions</div>\n");
      out.write("		</span>\n");
      out.write("		<span class=\"mobile-menu\" id='UniTimeGWT:MobileMenuPanel'></span>\n");
      out.write("		");
 if (errorMsg!=null)  { 
      out.write("<div class='error'>");
      out.print( errorMsg );
      out.write("</div>");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		<span class='login'>\n");
      out.write("			<div id=\"login\">\n");
      out.write("				<div class=\"BrownBG\">\n");
      out.write("					<div class=\"H40px\"></div>\n");
      out.write("					<div><label>Username:</label></div>\n");
      out.write("					<div class=\"txtField\"><input type='text' name='username' value='");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("' aria-label='Enter user name'/></div>\n");
      out.write("					<div class=\"H20px\"></div>\n");
      out.write("					<div><label>Password:</label></div>\n");
      out.write("					<div class=\"txtField\"><input type='password' name='password' aria-label='Enter password'></div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bottom\"><img src=\"images/login_bg_2.jpg\"/><input id=\"submit\" name=\"submit\" type=\"image\" src=\"images/login_bg_3.jpg\" border=\"0\" align=\"top\" value=\"log in\" alt=\"Submit login information.\"><img src=\"images/login_bg_4.jpg\"/></div>\n");
      out.write("			</div>\n");
      out.write("		</span>\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	</span>\n");
      out.write("</FORM>\n");
      out.write("		\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 StartupService service = (StartupService)SpringApplicationContextHolder.getBean("startupService"); 
      out.write('\n');
 if (service.getInitializationException() != null) { 
      out.write("\n");
      out.write("<div class='unitime-InitializationError'>\n");
      out.write("	UniTime ");
      out.print(Constants.getVersion());
      out.write(" failed to start up properly, please check the application log for more details.<br/>\n");
      out.write("	");

	Throwable t = service.getInitializationException();
	while (t != null) {
		String clazz = t.getClass().getName();
		if (clazz.indexOf('.') >= 0) clazz = clazz.substring(1 + clazz.lastIndexOf('.'));
		out.println("<br>" + clazz + ": " + t.getMessage() + (t.getStackTrace() != null && t.getStackTrace().length > 0 ? " (at " + t.getStackTrace()[0].getFileName() + ":" + t.getStackTrace()[0].getLineNumber() + ")": ""));
		t = t.getCause();
	}
	
      out.write("\n");
      out.write("</div>	\n");
 } 
      out.write("\n");
      out.write("		\n");
      out.write("		<span class=\"unitime-Footer\">\n");
      out.write("			<span class=\"row\">\n");
      out.write("				<span class=\"cell middle\">\n");
      out.write("					<span id='UniTimeGWT:Version'></span>\n");
      out.write("					");
      if (_jspx_meth_tt_005fcopy_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</span>\n");
      out.write("			</span>\n");
      out.write("		</span>\n");
      out.write("		");
      if (_jspx_meth_tt_005fhasProperty_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		\n");
      out.write("\n");
      out.write("		");
 if (ApplicationProperties.getProperty("tmtbl.footer.external", "").trim().length()>0) { 
      out.write("\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, ApplicationProperties.getProperty("tmtbl.footer.external"), out, true);
      out.write('\n');
      out.write('	');
      out.write('	');
 } 
      out.write("\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_loc_005frtl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  loc:rtl
    org.unitime.localization.impl.IsRtlTag _jspx_th_loc_005frtl_005f0 = (org.unitime.localization.impl.IsRtlTag) _005fjspx_005ftagPool_005floc_005frtl.get(org.unitime.localization.impl.IsRtlTag.class);
    boolean _jspx_th_loc_005frtl_005f0_reused = false;
    try {
      _jspx_th_loc_005frtl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_loc_005frtl_005f0.setParent(null);
      int _jspx_eval_loc_005frtl_005f0 = _jspx_th_loc_005frtl_005f0.doStartTag();
      if (_jspx_eval_loc_005frtl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime-rtl.css\">");
          int evalDoAfterBody = _jspx_th_loc_005frtl_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_loc_005frtl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005floc_005frtl.reuse(_jspx_th_loc_005frtl_005f0);
      _jspx_th_loc_005frtl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_loc_005frtl_005f0, _jsp_getInstanceManager(), _jspx_th_loc_005frtl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f0 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f0_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f0.setParent(null);
      // /login.jsp(53,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f0.setName("tmtbl.global.info");
      int _jspx_eval_tt_005fhasProperty_005f0 = _jspx_th_tt_005fhasProperty_005f0.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f0);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageMessage'>");
          if (_jspx_meth_tt_005fproperty_005f0(_jspx_th_tt_005fhasProperty_005f0, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f0);
      _jspx_th_tt_005fhasProperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f0 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f0_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f0);
      // /login.jsp(54,38) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f0.setName("tmtbl.global.info");
      int _jspx_eval_tt_005fproperty_005f0 = _jspx_th_tt_005fproperty_005f0.doStartTag();
      if (_jspx_th_tt_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f0);
      _jspx_th_tt_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f1 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f1_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f1.setParent(null);
      // /login.jsp(56,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f1.setName("tmtbl.global.warn");
      int _jspx_eval_tt_005fhasProperty_005f1 = _jspx_th_tt_005fhasProperty_005f1.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f1);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageWarn'>");
          if (_jspx_meth_tt_005fproperty_005f1(_jspx_th_tt_005fhasProperty_005f1, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f1);
      _jspx_th_tt_005fhasProperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f1 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f1_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f1);
      // /login.jsp(57,35) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f1.setName("tmtbl.global.warn");
      int _jspx_eval_tt_005fproperty_005f1 = _jspx_th_tt_005fproperty_005f1.doStartTag();
      if (_jspx_th_tt_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f1);
      _jspx_th_tt_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f2 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f2_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f2.setParent(null);
      // /login.jsp(59,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f2.setName("tmtbl.global.error");
      int _jspx_eval_tt_005fhasProperty_005f2 = _jspx_th_tt_005fhasProperty_005f2.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f2);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageError'>");
          if (_jspx_meth_tt_005fproperty_005f2(_jspx_th_tt_005fhasProperty_005f2, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f2);
      _jspx_th_tt_005fhasProperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f2 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f2_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f2);
      // /login.jsp(60,36) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f2.setName("tmtbl.global.error");
      int _jspx_eval_tt_005fproperty_005f2 = _jspx_th_tt_005fproperty_005f2.doStartTag();
      if (_jspx_th_tt_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f2);
      _jspx_th_tt_005fproperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f0 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f0_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f0.setParent(null);
      // /login.jsp(62,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setPrefix("tmtbl.page.warn.");
      // /login.jsp(62,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setStyle("unitime-PageWarn");
      // /login.jsp(62,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setPage("login");
      int _jspx_eval_tt_005fpage_002dwarning_005f0 = _jspx_th_tt_005fpage_002dwarning_005f0.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f0);
      _jspx_th_tt_005fpage_002dwarning_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f1 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f1_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f1.setParent(null);
      // /login.jsp(63,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setPrefix("tmtbl.page.info.");
      // /login.jsp(63,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setStyle("unitime-PageMessage");
      // /login.jsp(63,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setPage("login");
      int _jspx_eval_tt_005fpage_002dwarning_005f1 = _jspx_th_tt_005fpage_002dwarning_005f1.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f1);
      _jspx_th_tt_005fpage_002dwarning_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f2 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f2_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f2.setParent(null);
      // /login.jsp(64,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setPrefix("tmtbl.page.error.");
      // /login.jsp(64,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setStyle("unitime-PageError");
      // /login.jsp(64,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setPage("login");
      int _jspx_eval_tt_005fpage_002dwarning_005f2 = _jspx_th_tt_005fpage_002dwarning_005f2.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f2);
      _jspx_th_tt_005fpage_002dwarning_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /login.jsp(83,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("login");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(97,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty SPRING_SECURITY_LAST_EXCEPTION.message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class='error'>Authentication failed: ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write(".</div>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /login.jsp(98,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SPRING_SECURITY_LAST_EXCEPTION.message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /login.jsp(105,69) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty SPRING_SECURITY_LAST_USERNAME}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /login.jsp(105,125) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SPRING_SECURITY_LAST_USERNAME}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /login.jsp(113,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SUGGEST_PASSWORD_RESET}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<span class='forgot'><a href='gwt.jsp?page=password&reset=1' class='unitime-FooterLink'>Forgot your password?</a></span>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fcopy_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:copy
    org.unitime.timetable.tags.Copyright _jspx_th_tt_005fcopy_005f0 = (org.unitime.timetable.tags.Copyright) _005fjspx_005ftagPool_005ftt_005fcopy_0026_005fbr_005fnobody.get(org.unitime.timetable.tags.Copyright.class);
    boolean _jspx_th_tt_005fcopy_005f0_reused = false;
    try {
      _jspx_th_tt_005fcopy_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fcopy_005f0.setParent(null);
      // /login.jsp(125,5) name = br type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fcopy_005f0.setBr(false);
      int _jspx_eval_tt_005fcopy_005f0 = _jspx_th_tt_005fcopy_005f0.doStartTag();
      if (_jspx_th_tt_005fcopy_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fcopy_0026_005fbr_005fnobody.reuse(_jspx_th_tt_005fcopy_005f0);
      _jspx_th_tt_005fcopy_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fcopy_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fcopy_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f3 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f3_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f3.setParent(null);
      // /login.jsp(129,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f3.setName("tmtbl.page.disclaimer");
      int _jspx_eval_tt_005fhasProperty_005f3 = _jspx_th_tt_005fhasProperty_005f3.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f3);
        }
        do {
          out.write("\n");
          out.write("			<span class='unitime-Disclaimer'>");
          if (_jspx_meth_tt_005fproperty_005f3(_jspx_th_tt_005fhasProperty_005f3, _jspx_page_context))
            return true;
          out.write("</span>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f3);
      _jspx_th_tt_005fhasProperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f3 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f3_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f3);
      // /login.jsp(130,36) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f3.setName("tmtbl.page.disclaimer");
      int _jspx_eval_tt_005fproperty_005f3 = _jspx_th_tt_005fproperty_005f3.doStartTag();
      if (_jspx_th_tt_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f3);
      _jspx_th_tt_005fproperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f3_reused);
    }
    return false;
  }
}
