/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-05 05:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.unitime.timetable.ApplicationProperties;
import org.unitime.timetable.util.Constants;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tld/localization.tld", Long.valueOf(1596536222000L));
    _jspx_dependants.put("jar:file:/home/nhtlong/tomcat-stuffed/webapps/ROOT/WEB-INF/lib/struts-taglib-1.3.10.jar!/META-INF/tld/struts-logic.tld", Long.valueOf(1227893410000L));
    _jspx_dependants.put("/WEB-INF/tld/timetable.tld", Long.valueOf(1580200626000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.10.jar", Long.valueOf(1580200624000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.unitime.timetable.ApplicationProperties");
    _jspx_imports_classes.add("org.unitime.timetable.util.Constants");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005floc_005frtl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fnotHasProperty_0026_005fuser_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005foffering_002dlocks_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005ftime_002dstamp_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fcopy_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fupdate_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005floc_005frtl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fnotHasProperty_0026_005fuser_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005foffering_002dlocks_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005ftime_002dstamp_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fcopy_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fupdate_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005floc_005frtl.release();
    _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.release();
    _005fjspx_005ftagPool_005ftt_005fnotHasProperty_0026_005fuser_005fname.release();
    _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.release();
    _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005foffering_002dlocks_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod.release();
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005ftime_002dstamp_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fcopy_005fnobody.release();
    _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fupdate_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<HTML>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	<title>UniTime ");
      out.print(Constants.VERSION);
      out.write("| University Timetabling Application</title>\n");
      out.write("	<link rel=\"shortcut icon\" href=\"images/timetabling.ico\" />\n");
      out.write("	<link type=\"text/css\" rel=\"stylesheet\" href=\"unitime/gwt/standard/standard.css\">\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime.css\">\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime-mobile.css\">\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"styles/timetabling.css\">\n");
      out.write("    ");
      if (_jspx_meth_loc_005frtl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_tt_005fhasProperty_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <script language=\"JavaScript\" type=\"text/javascript\" src=\"scripts/loading.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" language=\"javascript\" src=\"unitime/unitime.nocache.js\"></script>\n");
      out.write("</head>\n");
      out.write("<BODY class=\"unitime-Body\">\n");
      out.write("    <iframe src=\"javascript:''\" id=\"__gwt_historyFrame\" tabIndex=\"-1\" style=\"position:absolute;width:0;height:0;border:0\"></iframe>\n");
      out.write("    <iframe src=\"javascript:''\" id=\"__printingFrame\" tabIndex=\"-1\" style=\"position:absolute;width:0;height:0;border:0\"></iframe>\n");
      out.write("\n");
      out.write("	<span class='top-menu'>\n");
      out.write("    ");
      if (_jspx_meth_tt_005fnotHasProperty_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_tt_005fpropertyEquals_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_tt_005fpropertyEquals_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </span>\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_tt_005fhasProperty_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fhasProperty_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fhasProperty_005f3(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005fpage_002dwarning_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tt_005foffering_002dlocks_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  	\n");

	String sysMessage = ApplicationProperties.getProperty("tmtbl.system_message");
	boolean showBackground = (sysMessage == null || sysMessage.trim().isEmpty());
	if ("cas-logout".equals(request.getParameter("op"))) {
		sysMessage = "You have been successfully logged out of UniTime, click <a href='logout'>here</a> to log out of all other applications as well.";
		showBackground = false;
	}

      out.write('\n');
      //  tt:registration
      org.unitime.timetable.tags.Registration _jspx_th_tt_005fregistration_005f0 = (org.unitime.timetable.tags.Registration) _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod.get(org.unitime.timetable.tags.Registration.class);
      boolean _jspx_th_tt_005fregistration_005f0_reused = false;
      try {
        _jspx_th_tt_005fregistration_005f0.setPageContext(_jspx_page_context);
        _jspx_th_tt_005fregistration_005f0.setParent(null);
        // /main.jsp(84,0) name = method type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tt_005fregistration_005f0.setMethod("hasMessage");
        int _jspx_eval_tt_005fregistration_005f0 = _jspx_th_tt_005fregistration_005f0.doStartTag();
        if (_jspx_eval_tt_005fregistration_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_tt_005fregistration_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fregistration_005f0);
          }
          do {
            out.write('\n');
            out.write('	');
 showBackground = false; 
            out.write('\n');
            int evalDoAfterBody = _jspx_th_tt_005fregistration_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_tt_005fregistration_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_tt_005fregistration_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod.reuse(_jspx_th_tt_005fregistration_005f0);
        _jspx_th_tt_005fregistration_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fregistration_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fregistration_005f0_reused);
      }
      out.write("\n");
      out.write("\n");
      out.write("	<span class=\"unitime-Page\"><span class='row'>\n");
      out.write("	<span class='sidebar' id=\"unitime-SideMenu\">\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    		");
      if (_jspx_meth_tt_005fpropertyEquals_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <script language=\"JavaScript\" type=\"text/javascript\">\n");
      out.write("    	var sideMenu = document.getElementById(\"unitime-SideMenu\").getElementsByTagName(\"span\");\n");
      out.write("    	if (sideMenu.length > 0) {\n");
      out.write("    		var c = unescape(document.cookie);\n");
      out.write("    		var c_start = c.indexOf(\"UniTime:SideBar=\");\n");
      out.write("    		if (c_start >= 0) {\n");
      out.write("    			c_start = c.indexOf(\"|W:\", c_start) + 3;\n");
      out.write("    			var c_end = c.indexOf(\";\", c_start);\n");
      out.write("    			if (c_end < 0) c_end=c.length;\n");
      out.write("    			var width = c.substring(c_start, c_end);\n");
      out.write("    			sideMenu[0].style.width = width + \"px\";\n");
      out.write("    			// alert(c.substring(c.indexOf(\"UniTime:SideBar=\") + 16, c_end));\n");
      out.write("    		} else {\n");
      out.write("    			sideMenu[0].style.width = (sideMenu[0].id.indexOf(\"StackMenu\") >= 0 ? \"172px\" : \"152px\");\n");
      out.write("    		}\n");
      out.write("    	}\n");
      out.write("    </script>\n");
      out.write("	</span>\n");
      out.write("    <span class='main'><span class='body unitime-MainLogoFaded' id=\"unitime-Page\">\n");
      out.write("    	<span class=\"unitime-PageHeader\" id=\"unitime-Header\">\n");
      out.write("    		<span class=\"row\">\n");
      out.write("    			<span class=\"mobile-menu-button\" id='UniTimeGWT:MobileMenuButton'></span>\n");
      out.write("    			<a href='main.jsp' tabIndex=\"-1\" class=\"logo\"></a>\n");
      out.write("    			<span class=\"content\">\n");
      out.write("					<span id='UniTimeGWT:Title' class=\"title\">University Timetabling Application</span>\n");
      out.write("					<span class='unitime-Header'><span id='UniTimeGWT:Header' class=\"unitime-InfoPanel\"></span></span>\n");
      out.write("				</span>\n");
      out.write("			</span>\n");
      out.write("		</span>\n");
      out.write("	<span id='UniTimeGWT:Content' ");
      out.print((!showBackground ? "class='unitime-MainContent'" : "class='unitime-MainContent unitime-MainLogo'"));
      out.write(">\n");
      out.write("		<span class=\"mobile-menu\" id='UniTimeGWT:MobileMenuPanel'></span>\n");
      out.write("		");
 if (sysMessage != null && !sysMessage.trim().isEmpty()) { 
      out.write("\n");
      out.write("			<span class='messages'>\n");
      out.write("				<div class='WelcomeRowHead'>System Messages</div>\n");
      out.write("				<div class='message'>");
      out.print( sysMessage );
      out.write("</div>\n");
      out.write("			</span>\n");
      out.write("		");
 } 
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_tt_005fregistration_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	</span>\n");
      out.write("    </span><span class='footer' id=\"unitime-Footer\">\n");
      out.write("		<span class=\"unitime-Footer\">\n");
      out.write("			<span class=\"row\">\n");
      out.write("				<span class=\"cell left\">\n");
      out.write("					<span id='UniTimeGWT:Version'></span>\n");
      out.write("					");
      if (_jspx_meth_tt_005ftime_002dstamp_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</span>\n");
      out.write("    			");
      out.write("\n");
      out.write("				<span class=\"cell middle\">");
      if (_jspx_meth_tt_005fcopy_005f0(_jspx_page_context))
        return;
      out.write("</span>\n");
      out.write("				<span class=\"cell right\">");
      if (_jspx_meth_tt_005fregistration_005f3(_jspx_page_context))
        return;
      out.write("</span>\n");
      out.write("			</span>\n");
      out.write("		</span>\n");
      out.write("		");
      if (_jspx_meth_tt_005fhasProperty_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	</span>\n");
      out.write("</span></span></span>\n");
      out.write("	\n");
      out.write("</BODY>\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\n");
      out.write("	if (parent && parent.hideGwtDialog && parent.refreshPage) {\n");
      out.write("		parent.hideGwtDialog();\n");
      out.write("		parent.refreshPage();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_loc_005frtl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  loc:rtl
    org.unitime.localization.impl.IsRtlTag _jspx_th_loc_005frtl_005f0 = (org.unitime.localization.impl.IsRtlTag) _005fjspx_005ftagPool_005floc_005frtl.get(org.unitime.localization.impl.IsRtlTag.class);
    boolean _jspx_th_loc_005frtl_005f0_reused = false;
    try {
      _jspx_th_loc_005frtl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_loc_005frtl_005f0.setParent(null);
      int _jspx_eval_loc_005frtl_005f0 = _jspx_th_loc_005frtl_005f0.doStartTag();
      if (_jspx_eval_loc_005frtl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"styles/unitime-rtl.css\">");
          int evalDoAfterBody = _jspx_th_loc_005frtl_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_loc_005frtl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005floc_005frtl.reuse(_jspx_th_loc_005frtl_005f0);
      _jspx_th_loc_005frtl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_loc_005frtl_005f0, _jsp_getInstanceManager(), _jspx_th_loc_005frtl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f0 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f0_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f0.setParent(null);
      // /main.jsp(40,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f0.setName("tmtbl.custom.css");
      int _jspx_eval_tt_005fhasProperty_005f0 = _jspx_th_tt_005fhasProperty_005f0.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f0);
        }
        do {
          out.write("\n");
          out.write("		<LINK rel=\"stylesheet\" type=\"text/css\" href=\"%tmtbl.custom.css%\" />\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f0);
      _jspx_th_tt_005fhasProperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fnotHasProperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:notHasProperty
    org.unitime.timetable.tags.NotHasProperty _jspx_th_tt_005fnotHasProperty_005f0 = (org.unitime.timetable.tags.NotHasProperty) _005fjspx_005ftagPool_005ftt_005fnotHasProperty_0026_005fuser_005fname.get(org.unitime.timetable.tags.NotHasProperty.class);
    boolean _jspx_th_tt_005fnotHasProperty_005f0_reused = false;
    try {
      _jspx_th_tt_005fnotHasProperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fnotHasProperty_005f0.setParent(null);
      // /main.jsp(51,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fnotHasProperty_005f0.setName("unitime.menu.style");
      // /main.jsp(51,4) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fnotHasProperty_005f0.setUser(true);
      int _jspx_eval_tt_005fnotHasProperty_005f0 = _jspx_th_tt_005fnotHasProperty_005f0.doStartTag();
      if (_jspx_eval_tt_005fnotHasProperty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fnotHasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fnotHasProperty_005f0);
        }
        do {
          out.write("\n");
          out.write("	   	<span id='UniTimeGWT:DynamicTopMenu' style=\"display: block; height: 23px;\" ></span>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tt_005fnotHasProperty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fnotHasProperty_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fnotHasProperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fnotHasProperty_0026_005fuser_005fname.reuse(_jspx_th_tt_005fnotHasProperty_005f0);
      _jspx_th_tt_005fnotHasProperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fnotHasProperty_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fnotHasProperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f0 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f0_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f0.setParent(null);
      // /main.jsp(54,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f0.setName("unitime.menu.style");
      // /main.jsp(54,4) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f0.setUser(true);
      // /main.jsp(54,4) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f0.setValue("Dynamic On Top");
      int _jspx_eval_tt_005fpropertyEquals_005f0 = _jspx_th_tt_005fpropertyEquals_005f0.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f0);
        }
        do {
          out.write("\n");
          out.write("    	<span id='UniTimeGWT:DynamicTopMenu' style=\"display: block; height: 23px;\" ></span>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f0);
      _jspx_th_tt_005fpropertyEquals_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f1 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f1_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f1.setParent(null);
      // /main.jsp(57,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f1.setName("unitime.menu.style");
      // /main.jsp(57,4) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f1.setUser(true);
      // /main.jsp(57,4) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f1.setValue("Static On Top");
      int _jspx_eval_tt_005fpropertyEquals_005f1 = _jspx_th_tt_005fpropertyEquals_005f1.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f1);
        }
        do {
          out.write("\n");
          out.write("    	<span id='UniTimeGWT:TopMenu' style=\"display: block; height: 23px;\" ></span>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f1);
      _jspx_th_tt_005fpropertyEquals_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f1 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f1_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f1.setParent(null);
      // /main.jsp(62,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f1.setName("tmtbl.global.info");
      int _jspx_eval_tt_005fhasProperty_005f1 = _jspx_th_tt_005fhasProperty_005f1.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f1);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageMessage'>");
          if (_jspx_meth_tt_005fproperty_005f0(_jspx_th_tt_005fhasProperty_005f1, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f1);
      _jspx_th_tt_005fhasProperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f0 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f0_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f1);
      // /main.jsp(63,38) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f0.setName("tmtbl.global.info");
      int _jspx_eval_tt_005fproperty_005f0 = _jspx_th_tt_005fproperty_005f0.doStartTag();
      if (_jspx_th_tt_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f0);
      _jspx_th_tt_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f2 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f2_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f2.setParent(null);
      // /main.jsp(65,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f2.setName("tmtbl.global.warn");
      int _jspx_eval_tt_005fhasProperty_005f2 = _jspx_th_tt_005fhasProperty_005f2.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f2);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageWarn'>");
          if (_jspx_meth_tt_005fproperty_005f1(_jspx_th_tt_005fhasProperty_005f2, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f2);
      _jspx_th_tt_005fhasProperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f1 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f1_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f2);
      // /main.jsp(66,35) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f1.setName("tmtbl.global.warn");
      int _jspx_eval_tt_005fproperty_005f1 = _jspx_th_tt_005fproperty_005f1.doStartTag();
      if (_jspx_th_tt_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f1);
      _jspx_th_tt_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f3 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f3_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f3.setParent(null);
      // /main.jsp(68,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f3.setName("tmtbl.global.error");
      int _jspx_eval_tt_005fhasProperty_005f3 = _jspx_th_tt_005fhasProperty_005f3.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f3);
        }
        do {
          out.write("\n");
          out.write("    	<div class='unitime-PageError'>");
          if (_jspx_meth_tt_005fproperty_005f2(_jspx_th_tt_005fhasProperty_005f3, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f3);
      _jspx_th_tt_005fhasProperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f2 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f2_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f3);
      // /main.jsp(69,36) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f2.setName("tmtbl.global.error");
      int _jspx_eval_tt_005fproperty_005f2 = _jspx_th_tt_005fproperty_005f2.doStartTag();
      if (_jspx_th_tt_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f2);
      _jspx_th_tt_005fproperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f0 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f0_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f0.setParent(null);
      // /main.jsp(71,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setPrefix("tmtbl.page.warn.");
      // /main.jsp(71,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setStyle("unitime-PageWarn");
      // /main.jsp(71,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f0.setPage("main");
      int _jspx_eval_tt_005fpage_002dwarning_005f0 = _jspx_th_tt_005fpage_002dwarning_005f0.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f0);
      _jspx_th_tt_005fpage_002dwarning_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f1 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f1_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f1.setParent(null);
      // /main.jsp(72,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setPrefix("tmtbl.page.info.");
      // /main.jsp(72,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setStyle("unitime-PageMessage");
      // /main.jsp(72,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f1.setPage("main");
      int _jspx_eval_tt_005fpage_002dwarning_005f1 = _jspx_th_tt_005fpage_002dwarning_005f1.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f1);
      _jspx_th_tt_005fpage_002dwarning_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpage_002dwarning_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:page-warning
    org.unitime.timetable.tags.PageWarning _jspx_th_tt_005fpage_002dwarning_005f2 = (org.unitime.timetable.tags.PageWarning) _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.get(org.unitime.timetable.tags.PageWarning.class);
    boolean _jspx_th_tt_005fpage_002dwarning_005f2_reused = false;
    try {
      _jspx_th_tt_005fpage_002dwarning_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpage_002dwarning_005f2.setParent(null);
      // /main.jsp(73,1) name = prefix type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setPrefix("tmtbl.page.error.");
      // /main.jsp(73,1) name = style type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setStyle("unitime-PageError");
      // /main.jsp(73,1) name = page type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpage_002dwarning_005f2.setPage("main");
      int _jspx_eval_tt_005fpage_002dwarning_005f2 = _jspx_th_tt_005fpage_002dwarning_005f2.doStartTag();
      if (_jspx_th_tt_005fpage_002dwarning_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpage_002dwarning_0026_005fstyle_005fprefix_005fpage_005fnobody.reuse(_jspx_th_tt_005fpage_002dwarning_005f2);
      _jspx_th_tt_005fpage_002dwarning_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpage_002dwarning_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fpage_002dwarning_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005foffering_002dlocks_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:offering-locks
    org.unitime.timetable.tags.OfferingLocks _jspx_th_tt_005foffering_002dlocks_005f0 = (org.unitime.timetable.tags.OfferingLocks) _005fjspx_005ftagPool_005ftt_005foffering_002dlocks_005fnobody.get(org.unitime.timetable.tags.OfferingLocks.class);
    boolean _jspx_th_tt_005foffering_002dlocks_005f0_reused = false;
    try {
      _jspx_th_tt_005foffering_002dlocks_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005foffering_002dlocks_005f0.setParent(null);
      int _jspx_eval_tt_005foffering_002dlocks_005f0 = _jspx_th_tt_005foffering_002dlocks_005f0.doStartTag();
      if (_jspx_th_tt_005foffering_002dlocks_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005foffering_002dlocks_005fnobody.reuse(_jspx_th_tt_005foffering_002dlocks_005f0);
      _jspx_th_tt_005foffering_002dlocks_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005foffering_002dlocks_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005foffering_002dlocks_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f2 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f2_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f2.setParent(null);
      // /main.jsp(90,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f2.setName("unitime.menu.style");
      // /main.jsp(90,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f2.setUser(true);
      // /main.jsp(90,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f2.setValue("Stack On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f2 = _jspx_th_tt_005fpropertyEquals_005f2.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f2);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:SideStackMenu' style=\"display: block;\" ></span>\n");
          out.write("	    	");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f2);
      _jspx_th_tt_005fpropertyEquals_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f3 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f3_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f3.setParent(null);
      // /main.jsp(93,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f3.setName("unitime.menu.style");
      // /main.jsp(93,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f3.setUser(true);
      // /main.jsp(93,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f3.setValue("Tree On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f3 = _jspx_th_tt_005fpropertyEquals_005f3.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f3);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:SideTreeMenu' style=\"display: block;\" ></span>\n");
          out.write("	    	");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f3);
      _jspx_th_tt_005fpropertyEquals_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f4 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f4_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f4.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f4.setParent(null);
      // /main.jsp(96,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f4.setName("unitime.menu.style");
      // /main.jsp(96,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f4.setUser(true);
      // /main.jsp(96,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f4.setValue("Static Stack On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f4 = _jspx_th_tt_005fpropertyEquals_005f4.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f4);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:StaticSideStackMenu' style=\"display: block;\" ></span>\n");
          out.write("		    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f4);
      _jspx_th_tt_005fpropertyEquals_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f4, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f5 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f5_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f5.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f5.setParent(null);
      // /main.jsp(99,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f5.setName("unitime.menu.style");
      // /main.jsp(99,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f5.setUser(true);
      // /main.jsp(99,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f5.setValue("Static Tree On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f5 = _jspx_th_tt_005fpropertyEquals_005f5.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f5);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:StaticSideTreeMenu' style=\"display: block;\" ></span>\n");
          out.write("		    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f5);
      _jspx_th_tt_005fpropertyEquals_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f5, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f6 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f6_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f6.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f6.setParent(null);
      // /main.jsp(102,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f6.setName("unitime.menu.style");
      // /main.jsp(102,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f6.setUser(true);
      // /main.jsp(102,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f6.setValue("Dynamic Stack On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f6 = _jspx_th_tt_005fpropertyEquals_005f6.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f6);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:SideStackMenu' style=\"display: block;\" ></span>\n");
          out.write("		    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f6);
      _jspx_th_tt_005fpropertyEquals_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f6, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fpropertyEquals_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:propertyEquals
    org.unitime.timetable.tags.PropertyEquals _jspx_th_tt_005fpropertyEquals_005f7 = (org.unitime.timetable.tags.PropertyEquals) _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.get(org.unitime.timetable.tags.PropertyEquals.class);
    boolean _jspx_th_tt_005fpropertyEquals_005f7_reused = false;
    try {
      _jspx_th_tt_005fpropertyEquals_005f7.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fpropertyEquals_005f7.setParent(null);
      // /main.jsp(105,6) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f7.setName("unitime.menu.style");
      // /main.jsp(105,6) name = user type = java.lang.Boolean reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f7.setUser(true);
      // /main.jsp(105,6) name = value type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fpropertyEquals_005f7.setValue("Dynamic Tree On Side");
      int _jspx_eval_tt_005fpropertyEquals_005f7 = _jspx_th_tt_005fpropertyEquals_005f7.doStartTag();
      if (_jspx_eval_tt_005fpropertyEquals_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fpropertyEquals_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fpropertyEquals_005f7);
        }
        do {
          out.write("\n");
          out.write("    			<span id='UniTimeGWT:SideTreeMenu' style=\"display: block;\" ></span>\n");
          out.write("		    ");
          int evalDoAfterBody = _jspx_th_tt_005fpropertyEquals_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fpropertyEquals_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fpropertyEquals_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fpropertyEquals_0026_005fvalue_005fuser_005fname.reuse(_jspx_th_tt_005fpropertyEquals_005f7);
      _jspx_th_tt_005fpropertyEquals_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fpropertyEquals_005f7, _jsp_getInstanceManager(), _jspx_th_tt_005fpropertyEquals_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fregistration_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:registration
    org.unitime.timetable.tags.Registration _jspx_th_tt_005fregistration_005f1 = (org.unitime.timetable.tags.Registration) _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod.get(org.unitime.timetable.tags.Registration.class);
    boolean _jspx_th_tt_005fregistration_005f1_reused = false;
    try {
      _jspx_th_tt_005fregistration_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fregistration_005f1.setParent(null);
      // /main.jsp(145,2) name = method type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fregistration_005f1.setMethod("hasMessage");
      int _jspx_eval_tt_005fregistration_005f1 = _jspx_th_tt_005fregistration_005f1.doStartTag();
      if (_jspx_eval_tt_005fregistration_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fregistration_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fregistration_005f1);
        }
        do {
          out.write("\n");
          out.write("			<span class='messages'>\n");
          out.write("				<div class='WelcomeRowHead'>Messages from UniTime</div>\n");
          out.write("				<div class='message'>");
          if (_jspx_meth_tt_005fregistration_005f2(_jspx_th_tt_005fregistration_005f1, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("			</span>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_tt_005fregistration_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fregistration_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fregistration_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod.reuse(_jspx_th_tt_005fregistration_005f1);
      _jspx_th_tt_005fregistration_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fregistration_005f1, _jsp_getInstanceManager(), _jspx_th_tt_005fregistration_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fregistration_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fregistration_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:registration
    org.unitime.timetable.tags.Registration _jspx_th_tt_005fregistration_005f2 = (org.unitime.timetable.tags.Registration) _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod_005fnobody.get(org.unitime.timetable.tags.Registration.class);
    boolean _jspx_th_tt_005fregistration_005f2_reused = false;
    try {
      _jspx_th_tt_005fregistration_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fregistration_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fregistration_005f1);
      // /main.jsp(148,25) name = method type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fregistration_005f2.setMethod("message");
      int _jspx_eval_tt_005fregistration_005f2 = _jspx_th_tt_005fregistration_005f2.doStartTag();
      if (_jspx_th_tt_005fregistration_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fmethod_005fnobody.reuse(_jspx_th_tt_005fregistration_005f2);
      _jspx_th_tt_005fregistration_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fregistration_005f2, _jsp_getInstanceManager(), _jspx_th_tt_005fregistration_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005ftime_002dstamp_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:time-stamp
    org.unitime.timetable.tags.TimeStamp _jspx_th_tt_005ftime_002dstamp_005f0 = (org.unitime.timetable.tags.TimeStamp) _005fjspx_005ftagPool_005ftt_005ftime_002dstamp_005fnobody.get(org.unitime.timetable.tags.TimeStamp.class);
    boolean _jspx_th_tt_005ftime_002dstamp_005f0_reused = false;
    try {
      _jspx_th_tt_005ftime_002dstamp_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005ftime_002dstamp_005f0.setParent(null);
      int _jspx_eval_tt_005ftime_002dstamp_005f0 = _jspx_th_tt_005ftime_002dstamp_005f0.doStartTag();
      if (_jspx_th_tt_005ftime_002dstamp_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005ftime_002dstamp_005fnobody.reuse(_jspx_th_tt_005ftime_002dstamp_005f0);
      _jspx_th_tt_005ftime_002dstamp_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005ftime_002dstamp_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005ftime_002dstamp_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fcopy_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:copy
    org.unitime.timetable.tags.Copyright _jspx_th_tt_005fcopy_005f0 = (org.unitime.timetable.tags.Copyright) _005fjspx_005ftagPool_005ftt_005fcopy_005fnobody.get(org.unitime.timetable.tags.Copyright.class);
    boolean _jspx_th_tt_005fcopy_005f0_reused = false;
    try {
      _jspx_th_tt_005fcopy_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fcopy_005f0.setParent(null);
      int _jspx_eval_tt_005fcopy_005f0 = _jspx_th_tt_005fcopy_005f0.doStartTag();
      if (_jspx_th_tt_005fcopy_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fcopy_005fnobody.reuse(_jspx_th_tt_005fcopy_005f0);
      _jspx_th_tt_005fcopy_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fcopy_005f0, _jsp_getInstanceManager(), _jspx_th_tt_005fcopy_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fregistration_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:registration
    org.unitime.timetable.tags.Registration _jspx_th_tt_005fregistration_005f3 = (org.unitime.timetable.tags.Registration) _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fupdate_005fnobody.get(org.unitime.timetable.tags.Registration.class);
    boolean _jspx_th_tt_005fregistration_005f3_reused = false;
    try {
      _jspx_th_tt_005fregistration_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fregistration_005f3.setParent(null);
      // /main.jsp(161,29) name = update type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fregistration_005f3.setUpdate(true);
      int _jspx_eval_tt_005fregistration_005f3 = _jspx_th_tt_005fregistration_005f3.doStartTag();
      if (_jspx_th_tt_005fregistration_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fregistration_0026_005fupdate_005fnobody.reuse(_jspx_th_tt_005fregistration_005f3);
      _jspx_th_tt_005fregistration_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fregistration_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fregistration_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fhasProperty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:hasProperty
    org.unitime.timetable.tags.HasProperty _jspx_th_tt_005fhasProperty_005f4 = (org.unitime.timetable.tags.HasProperty) _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.get(org.unitime.timetable.tags.HasProperty.class);
    boolean _jspx_th_tt_005fhasProperty_005f4_reused = false;
    try {
      _jspx_th_tt_005fhasProperty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fhasProperty_005f4.setParent(null);
      // /main.jsp(164,2) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fhasProperty_005f4.setName("tmtbl.page.disclaimer");
      int _jspx_eval_tt_005fhasProperty_005f4 = _jspx_th_tt_005fhasProperty_005f4.doStartTag();
      if (_jspx_eval_tt_005fhasProperty_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tt_005fhasProperty_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tt_005fhasProperty_005f4);
        }
        do {
          out.write("\n");
          out.write("			<span class='unitime-Disclaimer'>");
          if (_jspx_meth_tt_005fproperty_005f3(_jspx_th_tt_005fhasProperty_005f4, _jspx_page_context))
            return true;
          out.write("</span>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_tt_005fhasProperty_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tt_005fhasProperty_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tt_005fhasProperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fhasProperty_0026_005fname.reuse(_jspx_th_tt_005fhasProperty_005f4);
      _jspx_th_tt_005fhasProperty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fhasProperty_005f4, _jsp_getInstanceManager(), _jspx_th_tt_005fhasProperty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tt_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tt_005fhasProperty_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tt:property
    org.unitime.timetable.tags.Property _jspx_th_tt_005fproperty_005f3 = (org.unitime.timetable.tags.Property) _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.get(org.unitime.timetable.tags.Property.class);
    boolean _jspx_th_tt_005fproperty_005f3_reused = false;
    try {
      _jspx_th_tt_005fproperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tt_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tt_005fhasProperty_005f4);
      // /main.jsp(165,36) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tt_005fproperty_005f3.setName("tmtbl.page.disclaimer");
      int _jspx_eval_tt_005fproperty_005f3 = _jspx_th_tt_005fproperty_005f3.doStartTag();
      if (_jspx_th_tt_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftt_005fproperty_0026_005fname_005fnobody.reuse(_jspx_th_tt_005fproperty_005f3);
      _jspx_th_tt_005fproperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tt_005fproperty_005f3, _jsp_getInstanceManager(), _jspx_th_tt_005fproperty_005f3_reused);
    }
    return false;
  }
}
